### ISSUE TITLE
Norton flagged and pulled vst3

### ISSUE THREAD

**Issue by Dorcia1** [Kiriki-liszt/JS_Inflator#1]
Looking forward to this plugin. Unfortunately Norton flagged and pulled it immediately. I don't mess around with flagged files. Any idea why?

**Comment by Kiriki-liszt** [comment]
Hello! I assume it's related to digital signing a dynamic libraries. This is my first time distributing a compiled product, I may be ignorant =) Currently figuring out how!

**Comment by Kiriki-liszt** [comment]
Before trying anything, I just ran a online virus scan for which kind of flag it has, but nothing came up. 
May I ask you what Norton said for this?
Here is online Virus Total log that I've tested:
https://www.virustotal.com/gui/file/954187002a07d2222ee9919cdd6d2f1324af3ea71ecce83e81d56374e7aa8b54

**Comment by Dorcia1** [comment]
Thanks for getting back to me. Very strange. I tried to replicate it and
when I downloaded it this time Norton had no problem and I double scanned
it, no threats detected. So now all I have to do is actually use it in a
mix. Thanks so much for the free plug!

**Comment by Kiriki-liszt** [comment]
That's very nice! Thank you for feedback and have a nice day!
