### ISSUE TITLE
GUI errors

### ISSUE THREAD

**Issue by fjgh36** [Kiriki-liszt/JS_Inflator#10]
1：When the plug-in is opened, the gui always jumps once, from large to small,
2：There is always a 1 second delay when you select any other size
win7    S1

Hope you  to optimize the new GUI, thanks!

**Comment by fjgh36** [comment]
The first problem is that the graphics blink the moment they open,
Let me just add to problem number two,   I open the plugin ，select 125% and then close the plugin, when I open the plugin again it's at the very top of the host, I can't see the top interface, I can't drag,  and then it stays like that.  
I haven't tried the other ratios yet

WIN7   S1

**Comment by Kiriki-liszt** [comment]
Sorry for late reply. I was applying for Master’s Degree and just got rejected =)
Now I have some time left before going full job search.

prob 1 - Yes, it was side effect for halving a huge pixel images. I can work on that.
prob 2, I don't know any obvious reasons for that. Maybe resizing function of VSTGUI is not that efficient.

**Comment by fjgh36** [comment]
Never mind, thanks for your reply!



At 2023-05-31 15:59:22, "Kiriki Liszt - yg331" ***@***.***> wrote:

Sorry for late reply. I was applying for Master’s Degree and just got rejected =)
Now I have some time left before going full job search.

prob 1 - Yes, it was side effect for halving a huge pixel images. I can work on that.
prob 2, I don't know any obvious reasons for that. Maybe resizing function of VSTGUI is not that efficient.

**Comment by Kiriki-liszt** [comment]
Update!
Now plugin loads GUI at half size(Zoom : 100%), not going from full to half.
Check the latest Release v1.6.0. 

Have a nice day!
