### ISSUE TITLE
AU?

### ISSUE THREAD

**Issue by zenphyl** [Kiriki-liszt/JS_Inflator#11]
Not sure where to ask sorry, not expert.

Any chance of an .AU version? Thank you.

**Comment by Kiriki-liszt** [comment]
Hello! Thank you for your interest!

I actually tried to build AU, but VSTSDK 3.7.7. had a bug in AU wrapper and did not worked. 
Now Steinberg updated to VSTSDK3.7.8., I would retry for AU. 
When succeed, I'll leave a comment here.

Have a nice day =)

**Comment by Wyvest** [comment]
> Hello! Thank you for your interest!
> 
> I actually tried to build AU, but VSTSDK 3.7.7. had a bug in AU wrapper and did not worked. Now Steinberg updated to VSTSDK3.7.8., I would retry for AU. When succeed, I'll leave a comment here.
> 
> Have a nice day =)

Any updates on this?

**Comment by zenphyl** [comment]
I'll add myself to the bump, would be great and still many users on High Sierra for Hackintosh + Nvidia, thank you!

**Comment by juhyeoncho** [comment]
I'm wating for au version :)

**Comment by xjgby** [comment]
I'm wating for au version

**Comment by autumoswitzerland** [comment]
Also interested in this! Thanks and let me know if I can help.

**Comment by autumoswitzerland** [comment]
With this free plugin you can run the JS Inflator VST3 even in Logic Pro:

https://kushview.net/element/

It can act as a wrapper for any plugin and plugin format.

**Comment by Kiriki-liszt** [comment]
Hey everyone!
@philiprikozen
@Wyvest
@juhyeoncho
@xjgby
@autumoswitzerland
Finally, the AUv2 build is now on latest beta release!!
Have a nice day!

**Comment by autumoswitzerland** [comment]
Nice, thank you! Also an AU version with the new UI design? :) PS: Always these requirements for free software...

**Comment by Kiriki-liszt** [comment]
Thanks!
After this beta phase, stable release will have the new GUI =)

**Comment by zenphyl** [comment]
> Hey everyone! @philiprikozen @Wyvest @juhyeoncho @xjgby @autumoswitzerland Finally, the AUv2 build is now on latest beta release!! Have a nice day!

Thank you! A nice day to you too
