### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by jonasborneland** [Kiriki-liszt/JS_Inflator#12]
Hi
How do I install this? 😊
Dosen't seem to work just to drag over the vst files in the vst3 folder on my mac, and I can't find any install instructions?
Maybe I'm just really overseeing something?

**Comment by jonasborneland** [comment]
This is on a macbook running intel Catalina

**Comment by Kiriki-liszt** [comment]
Hello! Thank you for your interest!

For Mac installation, download MACOS.zip from latest Release page 
[https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3/releases](https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3/releases)
then copy InflatorPackage.VST3 to:
>  /Library/Audio/Plug-Ins/VST3/

After placing .VST3, rescan plugins and now should show in any DAW using VSTs.
Please let me know if it doesn't work!

Have a nice day =)

**Comment by jonasborneland** [comment]
@Kiriki-liszt Thank you very much for the answer! Thats what I have done and it does not show up in Ableton.
I just realized I might have used a worng file - I just downloaded the whole source code and extracted the vst3 file and put it in the system folder... Now I did try again with the MACOS link you sent above.
When I opened ableton it had a security warning – I then opened mac settings and approved it, but after re-opening ableton, it still dosen't appear 😔

I have installed multiple vst's this way before.
"InflatorPackage.vst3" is in /Library/Audio/Plug-Ins/VST3/
and I have restarted my computer and rescanned ableton, and the ableton folder is set to system folder – but the plugin does not appear.
Does it only support 32bit? Else it's really strange that it dosent show up 😊

**Comment by jonasborneland** [comment]
@Kiriki-liszt Finally got it to work!! 🥳
The mac security was the issue, this command in terminal for whitelisting the vst app made it work 😊
`sudo xattr -r -d com.apple.quarantine /Library/Audio/Plug-Ins/VST3/InflatorPackage.vst3`

**Comment by Kiriki-liszt** [comment]
WOW! Glad that worked out!!
Never knew about MacOS security could be a problem.
Many thanks for letting me know how to, and I should share with others in main page.

Have a great day!!! 👍👍

**Comment by Knight-kuo** [comment]
Thanks for your work! But it's still not working on my mac, M1 Monterey, and I use Logic pro. I have put the file into the right folder, and I have run that code and rebooted my computer, but my daw still can't scan it, do you have any idea?

**Comment by Kiriki-liszt** [comment]
Hello! Thanks for your interest.
The Logic version, meaning AudioUnit version of this plugin is now released as beta!
You can check it out in v1.7.0.beta release.
Have a nice day!

**Comment by Knight-kuo** [comment]
Well, it seems my daw doesn't support it? I have put them into the right folders and whitelisted them both, but my daw still says that it's not compatible...

**Comment by Kiriki-liszt** [comment]
Oh... now that's strange.
Could you try these lines?
``` console
sudo codesign --force --sign - /Library/Audio/Plug-Ins/VST3/InflatorPackage.vst3  
sudo codesign --force --sign - /Library/Audio/Plug-Ins/Components/InflatorPackage.component  
```
These are for Codesigning plugins, different from "sudo xattr -r -d com.apple.quarantine ~" in readme.
Thanks!

**Comment by Knight-kuo** [comment]
OMG these two codes actually worked, now my daw can recognize the plugin, thanks a lot!❤️

**Comment by Kiriki-liszt** [comment]
Fantastic!
Have a nice day =)

**Comment by DoTheBeat** [comment]
Please let me know me how to switch VST3 for Windows to Twarch GUI. Thanks

**Comment by alejo0606** [comment]
como lo instalo en window ? quien me ayuda por favor

**Comment by pritvorshik** [comment]
> как его установить в Windows ? кто мне поможет, пожалуйста
1.Распакуйте версию для Windows из последней версии Release (JS_Inflator.vst3) и скопируйте в папку «C:\Program Files\Common Files\VST3».
2. Просканируй по новой плагины в DAW например в Ableton

Unzip Windows version from latest Release JS_Inflator.vst3  and copy to "C:\Program Files\Common Files\VST3".
Scan the plugins in your DAW, such as Ableton
