### ISSUE TITLE
Metering too rapid

### ISSUE THREAD

**Issue by IsaakCode** [Kiriki-liszt/JS_Inflator#13]
In both GUI versions I found the metering to be too quick. I think it needs to be optimized to be reacting more like a meter in a DAW (a bit slowed down, but also indicating the highest peak). You can look into VU or RMS meters, which are a bit slowed down / averaged / smoothed to be more useful for users.

**Comment by Kiriki-liszt** [comment]
Hello! Thank you for your interest!
Yes, the metering implementation is just plain dB value presenter now,
and I agree it should be more usable.
I think it can use some kind of env follower, with instant attack and slow release.
Also the red indicator for 0dBfs could be useful, have no idea now how to make it though.

I'll work on it, and leave comments here!
Have a nice day!

**Comment by Kiriki-liszt** [comment]
Hello! 
Now with version 2, the meterings are now following envelop detector with 0.3sec attack and 3sec release! 
Attack time might be changed to be faster, though. 
It took very long time to get on this, but worked through it.

Have a nice day!!
