### ISSUE TITLE
Plugin has very low level static noise always in the background

### ISSUE THREAD

**Issue by orthearc** [Kiriki-liszt/JS_Inflator#15]
hey there, loved your work on this one!
there is a static noise on a very low level that is always there.
added a screenshot to demonstrate:
<img width="1120" alt="image" src="https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3/assets/135601212/a209588c-ae15-4ec1-92ef-3f8744744cef">

i would appreciate it so much if you could investigate this and clean it up.
thank you so much for your hard work!

**Comment by Kiriki-liszt** [comment]
Hello! Thanks for your interest =)
That is 64bit floating point dither noise, from Airwindows plugins.
When I started to make plugins I thought that dither noise is one of secrets of Airwindows sound
(which later changed my mind that it is not),
and also Sonnox Limiter has Inflator section and dithers it after.
The dither for 32bit is also implemented.

I could make a option button for dither on/off in next release, maybe next to size option.
I'll leave comment here if so!

Have a nice day!

**Comment by Kiriki-liszt** [comment]
Hey! I just released new version, with floating point dither off!
Check it out if interested =)

**Comment by orthearc** [comment]
YOO thats sick! i cannot believe you remembered me! it is better now thanks so much!
i tried to do some testing with the oxford one - i did sine wave phase invert between your inflator and oxford's. found something oddly strange. if they were the same there would be nothing showing on the analyzer. would be insane if you could look into that? 
again youre a god thank you so much! @Kiriki-liszt 
<img width="998" alt="crazy" src="https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3/assets/135601212/c0adf405-500f-4470-97ce-2afa0f3ebc83">

**Comment by Kiriki-liszt** [comment]
Thanks for testing out!

Yes, the original JSFX Inflator is null at -120dB.
There's community version null at -270dB by [lewloiwc](https://forum.cockos.com/member.php?u=158136) at https://forum.cockos.com/showpost.php?p=2581992&postcount=201 
Two differences are 
1. effect == wet is reduced to 99.999955296% and 
2. The output below 0.000000000000000000000005551151231257827021181583 4045 is 0.  

I was not interested in these before, and still is, but maybe I might add that 99.999955296%.
If I do, I'll leave comment here!

Have a Nice day!!
