### ISSUE TITLE
New GUI

### ISSUE THREAD

**Issue by Lorencito34** [Kiriki-liszt/JS_Inflator#16]
Hello, I am a designer and I would like to give a professional look to the plugin, if someone can help me and collaborate together since I can't use vstsdk.  (I speak Spanish but I translate with the ee google translator).

**Comment by Kiriki-liszt** [comment]
Hello! Thanks for your interest and sorry for such long waiting.  
Last 6 months, I was applying to get a job, no luck so far =)

New GUI is always welcome!!
We can use this issue board for ideas, uploading zip files, and so on.
If still interested, I can always build your version of GUI!
Have a nice day!

**Comment by potroub** [comment]
> Hello! Thanks for your interest and sorry for such long waiting. Last 6 months, I was applying to get a job, no luck so far =)
> 
> New GUI is always welcome!! We can use this issue board for ideas, uploading zip files, and so on. If still interested, I can always build your version of GUI! Have a nice day!

Hi Kiriki-liszt

Been having an issue with the new GUI it is not working out for me with the latest version check in issues I've posted about it thanx

hope all is well 
PeaceR

**Comment by Kiriki-liszt** [comment]
> > Hello! Thanks for your interest and sorry for such long waiting. Last 6 months, I was applying to get a job, no luck so far =)
> > New GUI is always welcome!! We can use this issue board for ideas, uploading zip files, and so on. If still interested, I can always build your version of GUI! Have a nice day!
> 
> Hi Kiriki-liszt
> 
> Been having an issue with the new GUI it is not working out for me with the latest version check in issues I've posted about it thanx
> 
> hope all is well PeaceR

Hello!
The new GUI is now available in v1.7.0 release!
Please check it out =)
Have a nice day!

**Comment by potroub** [comment]
Thank You So much will try it out later tonight
Merci & Happy New Year
PeaceR


*Richard Le Gendre*
Ingénieur de son, SoundDesigner, Compositeur,
Réalisateur et Spécialiste Ableton Live.



*QuickMusic FactorySt**udio **Orange         *
135, Van Horne Montréal, Qc, Canada.
Tel : 514 282 0624
quickmusicfactory.ca
studioorange.ca
***@***.***

**Comment by dromer** [comment]
How do we switch to the other GUI?
