### ISSUE TITLE
Won't work in pro tools

### ISSUE THREAD

**Issue by alesstones** [Kiriki-liszt/JS_Inflator#19]
I do all my work in pro tools, but when I open this plugin crashes my daw straight away. I use blue patchwork to open vst plugins in pro tools, and they all work perfectly. This is the first vst I've encountered and does that, any way to fix this?
 By the way, it works in other daws and I can say this plugin It's a must have. Thanks

**Comment by Kiriki-liszt** [comment]
Hello! Thanks for your interest and wait for response.  
I've recreated some crashes and suspects memory buffer allocation failure.  
Just fixed that issue in latest beta release, please check it out =)
Or maybe, this plugin supports mono->mono / stereo->stereo. Not immersive ready...
Anyway if it continues, leave another comment here!
Have a nice day!
