### ISSUE TITLE
Oversampling

### ISSUE THREAD

**Issue by Yzrsah** [Kiriki-liszt/JS_Inflator#2]
Thank you so much for putting this together. Awesome stuff.

Could you please incorporate 8X oversampling? I'm sure you know how to do it already but there's also an example by SaulT on page 5 of the RCInflator thread.

8X Oversampled RCInflator:
https://stash.reaper.fm/v/43489/RCInflator-OS.jsfx

It would also be cool to have "Oxford Edition" and "Ideal Edition" like RCInflator implemented.

**Comment by Kiriki-liszt** [comment]
Thank you for your interest! 
Actually I never knew oversampling version was out there(as original Inflator does not oversample)!
Now I know, I'll find out how to adapt it, and maybe with some tweaking.

Thanks for letting me know!

**Comment by Kiriki-liszt** [comment]
Oversampling up to x8 now implemented!
I used diffrent filtering technique though. Some comparision on README.  
Planing to implement "Oxford / Ideal" first, then bandsplit function.  

Have a nice day!

**Comment by Yzrsah** [comment]
You did a perfect job with this. What can I say? Now we have something better than the original and I feel happy. :)

**Comment by Kiriki-liszt** [comment]
Band Split functionaloty added!
About "Oxford / Ideal" versions, is that their differences(wet knob, low level gate) are quite neglible as I looked in. 
The original Inflator even has some kind of dither-noiseshaping in the background, but didn't Implemented and stayed clean. 
Maybe I would add TPDF noise option later on, like version 2, but not now.

Thank you for idea of implementing oversamping and bandsplit.
Have a nice day!
