### ISSUE TITLE
cannot access the new GUI

### ISSUE THREAD

**Issue by potroub** [Kiriki-liszt/JS_Inflator#20]
Hi with previous version was able to change the GUI 

But now stuck with only the first version of the GUI and not able to use the new one

I'm on win 10 pro 64bit and ableton live 11 or 12

**Comment by potroub** [comment]
any niuze ? on this issue as I still cannot make the new GUI appear with last version v1.7.0.beta-2

Should I go back to earlier release ?

Thanx

**Comment by Kiriki-liszt** [comment]
Hello! 
Twarch GUI(the new gui) is now available in v1.7.0 release!
Please check it out =)
Have a nice day!!
