### ISSUE TITLE
missing buttons

### ISSUE THREAD

**Issue by davexnet** [Kiriki-liszt/JS_Inflator#21]
Hello - thanks for this great project.

I decided to try the twarch interface and I noticed the two round  buttons at the bottom, "effect" and "curve"
are missing.  I can use the mouse to drag over there location as normal and they're still functional.

Latest 64 bit Windows 10.  Am I missing a possible support program, or could this be because I'm using
motherboard graphics, no real GPU installed.

**Comment by Kiriki-liszt** [comment]
Hello!
Thanks for report!
My Win10 laptop displays both versions correctly, so no idea what could be a possible reason for that...
If previous versions does not work too, than it might be a error in VSTGUI SDK.
In that case, we'll have to wait for a update on SDK.
Please check it out tell us here!
Have a nice day =)

**Comment by davexnet** [comment]
Hello, yes,  problem is still there in v160 - the knobs are not there!
![image](https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3/assets/46010456/5678fa89-0bd6-48d7-a549-2cca5a0efbae)

**Comment by Kiriki-liszt** [comment]
Oh... that's, that is weird.
Just tested in my Windows laptop, in iZotope RX 10 loading VST3, and it showed knobs correctly.

<img width="480" alt="스크린샷 2024-02-23 오전 12 47 38" src="https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3/assets/107096260/f185fb8c-086f-4d12-957d-ea1d69de5386">

Maybe updating to latest RX might solve the problem, or just use 'Original GUI' version...
Post any updates here, please =)
Have a nice day!

**Comment by davexnet** [comment]
Yes I will switch to original GUI. which displays fine
I was wondering if the problem with the above is due some graphics facilty that I don't have available
as a consequence of not having a real GPU (motherboard graphics only).
I have the onboard ATI Radeon 3000 graphics, driver 8.970.100.9001 from 2015
