### ISSUE TITLE
Plugin won't load component is reported damaged

### ISSUE THREAD

**Issue by zinni97** [Kiriki-liszt/JS_Inflator#24]
Hey thanks for your work!

Looks like you have built a lovely plugin, sadly I couldn't get it to work so far. When I try to open the plugin MacOS pops up an error message which reports the .component file as broken and can't be opened. 

I tried with both GUI's and on Logic and Ableton, all the same. 

I'm running an M1 Max on Monterey.

**Comment by Kiriki-liszt** [comment]
Hi! Thanks for checking out!
As I'm in old intel mac, I can't reproduce the problem.
Maybe, codesigning the plugin might work - https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3?tab=readme-ov-file#how-to-use
> If it doesn't go well, configure security options in console as  
>  
> ``` console  
> sudo xattr -r -d com.apple.quarantine /Library/Audio/Plug-Ins/VST3/InflatorPackage.vst3  
> sudo xattr -r -d com.apple.quarantine /Library/Audio/Plug-Ins/Components/InflatorPackage.component
>
> sudo codesign --force --sign - /Library/Audio/Plug-Ins/VST3/InflatorPackage.vst3  
> sudo codesign --force --sign - /Library/Audio/Plug-Ins/Components/InflatorPackage.component  
> ```  
>  
> tested by @jonasborneland [here](https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3/issues/12#issuecomment-1616671177)

If it still doesn't work, a screenshot of error message will help.
+ AudioUnit validation page from Logic's plugin manager would be good, too!
<img width="548" alt="스크린샷 2024-04-14 오후 11 59 14" src="https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3/assets/107096260/53881f07-8129-4d3e-8148-6481bd9ca617">  

Have a nice day!

**Comment by zinni97** [comment]
Codesigning did it! 

I tried doing that before I opened the issue but apparently something failed or I made a mistake. 
It works now no problems, tried it with both GUI's too. 

Great plugin and thanks for your help!

Wishing you all the best and have a nice day.

**Comment by Kiriki-liszt** [comment]
Nice!!!
Thanks for reporting back =)
Have a good day!
