### ISSUE TITLE
Error in a header file

### ISSUE THREAD

**Issue by Mistahbrock** [Kiriki-liszt/JS_Inflator#25]
Hello

Today I dowloaded the code and there is some fishy and missing bit in this header :

InflatorPackageprocessor.h

<<<<<<< HEAD
		inline double CubicInterpolate(
=======
	private:
	};

	namespace ADAAConst
	{
		constexpr double TOL = 1.0e-5;
	}

	/** Base class for 1st-order ADAA */
	class ADAA1 : public StandardNL
	{
	public:
		ADAA1() = default;
		virtual ~ADAA1() {}

		void prepare() override
		{
			x1 = 0.0;
			ad1_x1 = 0.0;
		}

		inline double process(double x) noexcept override
		{
			// both x and y interpolation method take effect
			// interpolation at ill condition is better with simple linear - less quantization noise

			// TODO : x4 Interpolation?

			const size_t m7 = sizeof(double) * 7;

			memmove(x8 + 1, x8, m7); x8[0] = x;
			x = x8[4];

			bool illCondition = std::abs(x - x1) < ADAAConst::TOL;
			double ad1_x = nlFunc_AD1(x);

			double y = illCondition ?
				nlFunc(0.5 * (x + x1)) :
				(ad1_x - ad1_x1) / (x - x1);
			ad1_x1 = ad1_x;
			x1 = x;

			memmove(y8 + 1, y8, m7); y8[0] = y;
			double out = Lanczos_Half(y8[7], y8[6], y8[5], y8[4], y8[3], y8[2], y8[1], y8[0]);

			x = Lanczos_Half(x8[7], x8[6], x8[5], x8[4], x8[3], x8[2], x8[1], x8[0]);
			illCondition = std::abs(x - x1) < ADAAConst::TOL;
			ad1_x = nlFunc_AD1(x);

			double y0 = illCondition ?
				nlFunc(0.5 * (x + x1)) :
				(ad1_x - ad1_x1) / (x - x1);
			ad1_x1 = ad1_x;
			x1 = x;

			memmove(y8 + 1, y8, m7); y8[0] = y0;

			return out;
		}

	protected:
		virtual inline double nlFunc(double x) const noexcept { return func(x); }
		virtual inline double nlFunc_AD1(double x) const noexcept { return func_AD1(x); }

		static constexpr size_t A = 4;

		double x8[8] = { 0.0, };
		double y8[8] = { 0.0, };

		inline double kernel(double x)
		{
			if (fabs(x) < 1e-7)
				return 1;
			return A * sin(M_PI * x) * sin(M_PI * x / A) / (M_PI * M_PI * x * x);
		}

		// buffer = 0 1 2 3_4 5 6 7
		// want   = 3.5
		// i      = 0 1 2 3_4 5 6 7
		// S(3.5) = b[0]*L( 3.5) + b[1]*L( 2.5) + b[2]*L( 1.5) + b[3]*L( 0.5)
		//        + b[4]*L(-0.5) + b[5]*L(-1.5) + b[6]*L(-2.5) + b[7]*L(-3.5)
		const double LH[8]   = { kernel( 3.5 ), kernel( 2.5 ), kernel( 1.5 ), kernel( 0.5 ),
		                         kernel(-0.5 ), kernel(-1.5 ), kernel(-2.5 ), kernel(-3.5 ) };
		/*
		const double LH[8] = {
			-1.26608778212386683e-02,
			5.99094833772628801e-02,
			-1.66415231603508018e-01,
			6.20383013240694559e-01,
			6.20383013240694559e-01,
			-1.66415231603508018e-01,
			5.99094833772628801e-02,
			-1.26608778212386683e-02 };
		*/

		double Lanczos_Half(
			double y0, double y1, double y2, double y3,
			double y4, double y5, double y6, double y7) const
		{
			return y0 * LH[0] + y1 * LH[1] + y2 * LH[2] + y3 * LH[3]
				 + y4 * LH[4] + y5 * LH[5] + y6 * LH[6] + y7 * LH[7];
		}

		double CubicInterpolate(
>>>>>>> 1884726a328650b4162d4c30910d35747575271f

**Comment by Kiriki-liszt** [comment]
Hello! Thanks for checking it out!

These were my trial for ADAA antialiasing. 
It works but not finished.
ADAA has some kind of low cut, so I had to compensate with high shelf or dynamic oversample at least x4.
Something like this;
1. x1 + no ADAA -> no whole oversample  
2. x1 + ADAA -> x4 ADAA 
3. x2 + no ADAA -> x2 whole oversample 
4. x2 + ADAA -> x2 whole oversample & x2 ADAA 
5. x4 + no ADAA -> x4 whole oversample 
6. x4 + ADAA -> x4 whole oversample 

My Initial idea was to use interpolation for less latency, but come to think of it, FIR would be better.  

Now, actually, I lost interest in this... 
I might come later to finish it or completely remove it.
For latest release version, check it out at Release page.

Have a nice day =)

**Comment by Kiriki-liszt** [comment]
Hello!
I just updated to v2, and just removed the code for ADAA. 
Might come later for it, but it's clean now!

Have a nice day!
