### ISSUE TITLE
Problem with Undo (Ctrl+Z)

### ISSUE THREAD

**Issue by AntonyFlower** [Kiriki-liszt/JS_Inflator#26]
Problem with Undo (Ctrl+Z) in Ableton Live 12 when I use Audio Unit (MacOS 14.4.1)!
<img width="1512" alt="Inflator" src="https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3/assets/87662983/82573a3f-e194-42f3-8516-f861c64d0cc2">

**Comment by Kiriki-liszt** [comment]
Hello! 
Thanks for checking it out!

That was actually my fault with poor knowledge of VSTSDK when I started.  
I linked meter level to parameter, so the history function for Ctrl-Z saves all metering changed!

Now, I know how to get around this.  
I will fix this issue, and update it.  
When I do, I'll leave a comment about it.  

Thanks for reporting, and have a nice day!

**Comment by Kiriki-liszt** [comment]
Hello!
Just updated to v2 with this issue resolved! 
Please check and reply if Ctrl-Z are now working as intended.

Have a nice day!

**Comment by AntonyFlower** [comment]
Nice! Thank you!

**Comment by Kiriki-liszt** [comment]
Hello again!
Just updated to v2.0.1, for Ableton crash and VU meter for Twarch GUI. 
Please update before testing out!

Have a magnificent day =)
