### ISSUE TITLE
Installation.

### ISSUE THREAD

**Issue by Iamqthedon** [Kiriki-liszt/JS_Inflator#27]
How do I get the installation file?

**Comment by Kiriki-liszt** [comment]
Hello! 
Thanks for checking out!

I don't provide install files(exe, pkg, ...) instead gives the actual plugins only.  
You can read about it here;
https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3?tab=readme-ov-file#how-to-use

and the release page for downloading is at 
https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3/releases

Have a nice day!
