### ISSUE TITLE
Does not retain plugin settings within FL Studio's Patcher

### ISSUE THREAD

**Issue by fdigl** [Kiriki-liszt/JS_Inflator#28]
Windows 10 x64
FL Studio v21.2.3 b4004
11th gen Intel Core i7

JS Inflator v1.7.0 (Twarch GUI)

**Expected Outcome:**
Reopening a saved project that has a Patcher loaded in a mixer channel with an instance of JS Inflator loads the plugin with the settings saved at the time the project was saved.

**Actual Outcome:**
Reopening a saved project that has a Patcher loaded in a mixer channel with an instance of JS Inflator loads the plugin with the default settings.

**Steps to Reproduce:**
1. Start a new, empty FL Studio project.
2. Insert a Patcher on the Master mixer channel.
3. Insert and route JS Inflator within the Patcher window.
4. Modify the parameters within JS Inflator. In my testing, I manually entered the values in.
5. Save the FL Studio project, then close FL Studio.
6. Open FL Studio, then reload the project.
7. Inspect the instance of JS Inflator to check if the parameter values have reset.

**Comment by Kiriki-liszt** [comment]
Hello! 
Thanks for checking out!

I don't have any experience with FL, and does not know what patcher is, so it might take some time to look at it...
Sorry for that. 

As far as I know, when plugin is instantiated and saved, it saves 'states' as data file inside DAW and reloads it in the plugin.   
This process works very well in many other DAWs, like cubase and ableton, etc... 

While waiting, you might try alternative approach.  
Maybe calling my plugin inside of Waves StudioRack might work for saving settings!

I'll look into plugin state saving process more, looking if I missed something!
If I found one, I'll update it on here.

Have a nice day =)

**Comment by Kiriki-liszt** [comment]
Hello!
Just updated to v2, and reinforced state saving process by adding GUI setting save stage.  
Would you mind to test if this resolves your issue and reply back?

Have a nice day!

**Comment by fdigl** [comment]
Hi, I can confirm that version 2 does indeed fix this issue! Thanks for looking into this, now I can finally ditch "that paid plugin" :)

On another note - I did notice that the meters are no longer working in this version, but other functionality appears to work fine.

**Comment by Kiriki-liszt** [comment]
Thanks!
I just updated to version v2.0.1 for Ableton crash and VU meter for Twarch GUI!
Would you mind to test it out one last time?
Hope this fixes all problems =)

Have a magnificent day!

**Comment by fdigl** [comment]
Thanks! The meter now works, however the little menu button on the top doesn't - is this broken or not implemented yet?

**Comment by Kiriki-liszt** [comment]
Yes, the top menu bar of Twarch GUI is for look only...
There is no current plan for implementing it, too. 

I'll close this issue as main problem is solved!
Thanks for using my plugin!!!
