### ISSUE TITLE
Won't work in Logic Pro 11 (M1)

### ISSUE THREAD

**Issue by dddaaakkka** [Kiriki-liszt/JS_Inflator#32]
Hi there,
Thanks for the free plugin. However, it won't work in Logic Pro 11. (Works under Rosetta mode though.)

**Comment by Kiriki-liszt** [comment]
Hello!
Thanks for checking my plugin!

Currently, I'm on Intel mac to build and test plugin, and never knew Apple Silicon Native build is not working. 

I ordered newest iMac with M3 chip in it just yesterday, it will take about two to three weeks to ship! 
Apple Silicon Native builds will come in about a month. 

I'll leave comment on this issue after working versions are made. 

Have a nice day!! =)

**Comment by dddaaakkka** [comment]
Glad to hear that and thanks again! ;)

**Comment by Kiriki-liszt** [comment]
Hi!
Thanks for long waiting!
I just updated to v2.0.3 with Apple Silicon Native bugfix!
It opens and works fine in Logic Pro 10.8 - iMac M3, and should be same for any iMacs.
Please leave message here if the latest version works or not =)

Have a great day!

**Comment by dddaaakkka** [comment]
Hi!
I tried the updated file but it still doesn't work. :(
(I'm a Mac Mini(M2) Logic Pro 11 user by the way)

<img width="1920" alt="screen" src="https://github.com/Kiriki-liszt/JS_Inflator/assets/173519485/6685a339-e45a-4ff7-9e48-6e1b2f699dbe">

**Comment by Kiriki-liszt** [comment]
Just checked it with updated Logic Pro 11.0.1, it works fine.
Maybe, have you tried CodeSigning the plugin?
Apple automatically blocks any unregistered plugins by them, so we have to manually mark plugins(usually developed by small indie devs) as approved
It's in 'how to use' section of main repo page, [https://github.com/Kiriki-liszt/JS_Inflator?tab=readme-ov-file#how-to-use](https://github.com/Kiriki-liszt/JS_Inflator?tab=readme-ov-file#how-to-use)

> If it doesn't go well, CodeSign plugins in console as  
>
> ``` console  
> sudo xattr -r -d com.apple.quarantine /Library/Audio/Plug-Ins/VST3/JS_Inflator.vst3  
> sudo xattr -r -d com.apple.quarantine /Library/Audio/Plug-Ins/Components/JS_Inflator.component
>
> sudo codesign --force --sign - /Library/Audio/Plug-Ins/VST3/JS_Inflator.vst3  
> sudo codesign --force --sign - /Library/Audio/Plug-Ins/Components/JS_Inflator.component  
> ```  
>
> tested by @jonasborneland [here](https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3/issues/12#issuecomment-1616671177)

**Comment by dddaaakkka** [comment]
I entered those lines in the terminal app and it works. :)
Thanks a million!!!

**Comment by Kiriki-liszt** [comment]
Nice!! 
Have a great day!
