### ISSUE TITLE
Won't work on Bitwig 5.2b8

### ISSUE THREAD

**Issue by Cris--** [Kiriki-liszt/JS_Inflator#33]
Hi,

JS Inflator v2.0.2 didn't work in Bitwig 5.2b8, Windows 11.
The v2.0.1 works fine!

![Screenshot 2024-06-24 005407](https://github.com/Kiriki-liszt/JS_Inflator/assets/7994691/53bbbfce-21b1-4e5d-820a-651b9ba84aef)

**Comment by Kiriki-liszt** [comment]
Hello!
I found the cause of it, and yes I was able to fix it!
However, while testing out in Bitwig, the GUI had to be reopened to display correct type of GUI after the project reopened.
None of other DAWs did that, so I'll debug into that.

I'll leave comment on here after all things are sorted out!
Have a nice day! =)

**Comment by Kiriki-liszt** [comment]
Hi!
Just updated to version v2.0.2.1 that solves this problem!
You can check it out in latest Release page, and check if it works for you =)
Please leave comment how it goes!

Have a nice day!

**Comment by Cris--** [comment]
Works now!
