### ISSUE TITLE
Meters Not Working

### ISSUE THREAD

**Issue by EgonTwo** [Kiriki-liszt/JS_Inflator#37]
The meters in recent versions of JS_Inflator are not working on load. I have to turn it off and then back on for them to work. Signal processing seems fine.  Tested v2.0.2.2 and v 2.0.3.0. I've gone back to version 1.7.0

I'm using Cakewalk CBB, last version, in win10 up to date.

Thx E

**Comment by Kiriki-liszt** [comment]
Hello!
Thanks for checking it out!
I'll install and reproduce that bug, and see what happens.
Any progresses will be updated here =)

Have a good day!

**Comment by Kiriki-liszt** [comment]
Hello!
Just updated to v2.0.3.1 and this issue seems to solved, too!
Please check it out and comment how it goes =)

Have a nice day!
![화면 캡처 2024-07-26 021744](https://github.com/user-attachments/assets/b02eac35-a239-4f97-bf45-31644df9390d)

**Comment by EgonTwo** [comment]
Hi, 

Thanks for the quick turn around. 

The meters do work now.

But, unfortunately, I found another problem. When I use the Twarch GUI and I make adjustments with the knobs and faders, Cakewalk suddenly crashes. I'm not sure if the GUI is the issue. I also tried with different oversampling settings. No warning, the DAW just disappears/crashes.

:(

Thx E

**Comment by Kiriki-liszt** [comment]
Oh...
That needs another inspection!
I'll leave comment here if any progress is made on this new issue.

Have a great day!!

**Comment by Kiriki-liszt** [comment]
Hello!
Just fixed and updated to v2.0.3.2!
It was caused by VuMeter update routine, and now should work fine.
Please check it out one more time and comment how it goes =)

Have a great day!

**Comment by EgonTwo** [comment]
Thanks, it seems to be stable now. The meters work and I was not able to make it crash any more.  Thanks for the quick and good work!  E

**Comment by EgonTwo** [comment]
Hi,

Thanks, it seems to be fine now.

You can add Cakewalk By BandLab to your "Tested as working are" list.

I wonder, did you make the TWARCH GUI? I would have a small request to improve usability for that one. The indicator notch on the yellow knob is too light and tends to become invisible when turned to the left or right. If it could be made a more contrasting color that would be very helpful.  Also, if you could make the knobs easy to reset to default by double click, or [CTRL] click, that would be useful.

Thanks for the good work and a useful mixing tool.

​ıɥsɐqɐH ıuɐH
______________________________
My Projects:
http://habashi.ca/
https://corporal-salt.bandcamp.com/
https://blipobjectarray.bandcamp.com/
https://this-motor-oil.bandcamp.com/releases
https://tummydrums.bandcamp.com/
https://meatmakesmeat.bandcamp.com/releases
http://united-deviations.com/
https://www.instagram.com/visible.hani/
______________________________

On Friday, July 26, 2024 at 03:41:12 AM EDT, Aris Kiriki-Liszt == yg331 ***@***.***> wrote:

Hello!
Just fixed and updated to v2.0.3.2!
It was caused by VuMeter update routine, and now should work fine.
Please check it out one more time and comment how it goes =)

Have a great day!

**Comment by Kiriki-liszt** [comment]
Thanks!!
The alternative GUI(Twarch version) is made by Twarch, not me.
So I don't have original Photoshop or Illust file or so.
However, I could make Reset more doable! 
(Edit: It's already resetable with mac's command + click, windows' control + click)
That will be on next update, but update itself now has low priority.

Thanks for keeping in contact and have another nice day!
