### ISSUE TITLE
Logic pro Can't open JS-

### ISSUE THREAD

**Issue by AnsikBEAT** [Kiriki-liszt/JS_Inflator#39]
<img width="1659" alt="Screenshot 2024-07-30 at 3 29 15 PM" src="https://github.com/user-attachments/assets/898eae71-6799-4325-92d7-1cadc8b74e51">

Logic pro 11 / macbook air m1 / jsinflator ver. 2.0.3.2

**Comment by Kiriki-liszt** [comment]
Hello!
Thanks for checking it out!
Maybe, have you tried CodeSigning the plugin?
Apple automatically blocks any unregistered plugins by them, so we have to manually mark plugins(usually developed by small indie devs) as approved
It's in 'how to use' section of main repo page, [https://github.com/Kiriki-liszt/JS_Inflator?tab=readme-ov-file#macos](https://github.com/Kiriki-liszt/JS_Inflator?tab=readme-ov-file#macos)

> If it doesn't go well, CodeSign plugins in console as  
>
> ``` console  
> sudo xattr -r -d com.apple.quarantine /Library/Audio/Plug-Ins/VST3/JS_Inflator.vst3  
> sudo xattr -r -d com.apple.quarantine /Library/Audio/Plug-Ins/Components/JS_Inflator.component
>
> sudo codesign --force --sign - /Library/Audio/Plug-Ins/VST3/JS_Inflator.vst3  
> sudo codesign --force --sign - /Library/Audio/Plug-Ins/Components/JS_Inflator.component  
> ```  
>
> tested by @jonasborneland [here](https://github.com/Kiriki-liszt/JS_Inflator_to_VST2_VST3/issues/12#issuecomment-1616671177)

**Comment by Kiriki-liszt** [comment]
Just saw your youtube video, confirmed it works!
