### ISSUE TITLE
Multiband Mode

### ISSUE THREAD

**Issue by artegos** [Kiriki-liszt/JS_Inflator#4]
I tried your version and compared it to the original. It sounds insanely cool! In a blind test, my assistant and I chose your version. The only thing missing is the multiband mode, which we use a lot. Will you be able to implement it in future releases?

Anyway, even the current version sounds great and, as a mastering engineer, I would be happy to beta test and become an endorser!

Best regards, Alex

**Comment by Kiriki-liszt** [comment]
Thank you for testing my plugin out!!

The current version, v1.5.1, is already supporting Band Split mode, as well as Oversampling modes.
You can check it in the Release tab.
Please, Have fun and let me know how you felt about it =)

**Comment by Kiriki-liszt** [comment]
Case closed =)
