### ISSUE TITLE
Doesn't seem to work on M1 Mac running Monterey.

### ISSUE THREAD

**Issue by teleMA50c** [Kiriki-liszt/JS_Inflator#6]
DAWs seem to recognize something but Gatekeeper flags it as being from an unidentified developer - unfortunately disabling Gatekeeper doesn't fix anything as the plugin doesn't show up in the plugins list.  Tested in Ableton 11 and DaVinci Resolve.

Mac seems to recognize the file as an application whereas vst3 plugins are usually bundles.  Perhaps fixing this would also help.

**Comment by Kiriki-liszt** [comment]
Thank you for testing and letting me know! I really appreciate it =)
ARM cored Mac are always picky... Maybe I need a M1 Mac?
Now I know it's broken, I'll do some more search for it and build on next main release 1.6.0.
Have a nice day!

**Comment by Kiriki-liszt** [comment]
Updated with Xcode settings to 'Standard Architectures'!  
Hope this works.

**Comment by teleMA50c** [comment]
I think in general the build for Mac needs some foundational housekeeping - as it stands Ableton doesn't seem to be able to recognize a developer, even on my Intel machine.  The file should probably be called "JSInflator.vst3" - the fact that it's called "InflatorPackage.vst3" makes me question whether it's stuck somewhere between being an installer package and the actual VST3.  It might not be and I could be doing this all wrong but there are many companies that release their plugins for "drag-and-drop" install and unfortunately yours does not seem to work, at least not as seamlessly as theirs do.

**Comment by Kiriki-liszt** [comment]
Sorry for late reply. I was applying for Master’s Degree and just got rejected =)
Now I have some time left before going full job search.

About filename, I literally created the project files with "project name = InflatorPackage" option, not "JSInflator".
That means this plugin is called 'JS Inflator' in Github, internet, etc, but inside the plugin file - the 'name attribute' is 'InflatorPackage'.
The name "JSInflator" was made just before I uploaded whole project into Github.
I still search for my plugin as 'package' in my daws =)

About drag-and-drop, my Intel mac works drag-and-drop... 
Still have no idea why build for M1 on Intel machine is not working.

**Comment by jonasborneland** [comment]
Hi @teleMA50c 
This one helped me. Try to bypass the mac security with this command in the terminal app
`sudo xattr -r -d com.apple.quarantine /Library/Audio/Plug-Ins/VST3/InflatorPackage.vst3`
