### ISSUE TITLE
Size problem with new GUI under Ableton Live

### ISSUE THREAD

**Issue by twarch** [Kiriki-liszt/JS_Inflator#8]
today I wanted to try the plugin on a bass but surprise:

![Capture d’écran (85)](https://user-images.githubusercontent.com/100294927/232142766-ea3a2f3a-c13f-494c-87e8-b927e7a55cd4.png)

it's a 2k screen on a laptop if that matters. I need to try on my studio computer tomorrow.

**Comment by Kiriki-liszt** [comment]
Oh, that was a miss...
I'm guessing it's a problem from resizing routine.  
Since original PNGs are large in pixels, I just halfed the plugin window -> then resizing factors like 75% is applied.  
I could make a half sized PNGs and try it again.

**Comment by twarch** [comment]
Ableton make strange things sometimes... If I double click somewhere in the "bottom line", the gui becomes full and works...

**Comment by Kiriki-liszt** [comment]
Update!
Now plugin loads GUI at half size(Zoom : 100%), not going from full to half.
Check the latest Release v1.6.0.

Have a nice day!
